### ISSUE TITLE
How is SNR in ALL_ACTIONS determined?

### ISSUE THREAD

**Issue by sun9876543** [juanaznarp94/DynamicTPolicy-LoRa#10]
and max_packages

**Comment by LauraAcostaG** [comment]
The SNR values in ALL_ACTIONS are derived based on the relationship between the SF and the signal's robustness against noise. Higher SFs allow decoding at lower SNR thresholds, while lower SFs require better SNR. These thresholds are defined in LoRaWAN specification that define the minimum SNR required for successful packet decoding for each SF https://www.thethingsnetwork.org/docs/lorawan/rssi-and-snr/.

The max_packets field represents the maximum number of packets that can be transmitted for a given payload size. The maximum payload size depends on the data rate parameters (SF, BW, etc.) and is specified in the LoRaWAN standard.

**Comment by sun9876543** [comment]
Thanks for the answer, and it's great that you can provide code for the paper.

**Comment by juanaznarp94** [comment]
Dear Sun, I close this resolved issue. Please let us know if you have more questions. We are happy to help. PS: If you find our implementation useful, we would be grateful if you can cite the paper.
